import {
  eventTemplateSchema,
  scenarioManifestSchema,
  stateDeltaSchema,
  type EventTemplate,
  type OriginId,
  type ScenarioManifest,
  type StateDelta,
} from "@/lib/game/schemas";

function delta(overrides: Partial<StateDelta> = {}): StateDelta {
  return stateDeltaSchema.parse({
    minutesElapsed: 20,
    location: null,
    occupation: null,
    moneyDelta: 0,
    healthDelta: 0,
    healthCondition: null,
    addItems: [],
    removeItemIds: [],
    relationshipDeltas: [],
    reputationDeltas: { household: 0, market: 0, administration: 0 },
    skillDeltas: {
      memory: 0,
      reasoning: 0,
      socialJudgment: 0,
      professionalPotential: 0,
      physical: 0,
      luck: 0,
    },
    addQuests: [],
    completeQuestIds: [],
    addRisks: [],
    resolveRiskIds: [],
    death: null,
    ...overrides,
  });
}

function ending(
  id: string,
  title: string,
  summary: string,
  sourceIds: string[],
): NonNullable<EventTemplate["choices"][number]["consequence"]["ending"]> {
  return {
    id,
    title,
    summary,
    classification: "叙事虚构",
    sourceIds,
  };
}

export const phase10ScenarioManifest: ScenarioManifest = scenarioManifestSchema.parse({
  scenarioId: "tang-changan-742",
  contentVersion: "10.0.0",
  era: { start: 742, end: 742 },
  locations: ["western-market", "craft-ward", "jingzhao-fu"],
  origins: ["merchant", "craft", "clerk"],
  evidencePolicy: "source_required",
  firstEventByOrigin: {
    merchant: "merchant-ledger-mark",
    craft: "craft-material-shortfall",
    clerk: "clerk-ambiguous-place",
  },
});

const rawEvents: EventTemplate[] = [
  {
    eventId: "merchant-ledger-mark",
    chapterId: "merchant-first-ledger",
    originIds: ["merchant"],
    title: "账纸上的陌生印记",
    classification: "合理重建",
    prerequisites: [
      { kind: "origin_is", originId: "merchant" },
      { kind: "turn_between", min: 0, max: 0 },
      { kind: "location_is", locationId: "western-market" },
    ],
    freeTextChoiceId: "choice-1",
    evidenceRefs: ["S-003", "S-004", "S-005"],
    publicationStatus: "published",
    choices: [
      {
        id: "choice-1",
        label: "逐项核对账纸与货签",
        intent: "先确认可见证据，再向家人提问",
        risk: "low",
        consequence: {
          key: "merchant-ledger-audit",
          summary: "你先核对账纸，避免把陌生印记直接解释成欠账。",
          stateDelta: delta({
            minutesElapsed: 25,
            relationshipDeltas: [{ id: "household-steward", label: "家庭管事", delta: 1 }],
            skillDeltas: { memory: 1, reasoning: 0, socialJudgment: 0, professionalPotential: 0, physical: 0, luck: 0 },
          }),
          relationshipMemories: [{
            relationshipId: "household-steward",
            summary: "家庭管事记得你先查证再开口。",
            valence: "positive",
          }],
          riskClockDeltas: [{ id: "market-deadline", label: "西市交割期限", delta: 1, threshold: 5, resolve: false }],
          nextEventId: "merchant-gate-window",
          ending: null,
        },
      },
      {
        id: "choice-2",
        label: "带着账纸直接赶往西市",
        intent: "抢在交易窗口关闭前寻找对应货物",
        risk: "medium",
        consequence: {
          key: "merchant-market-rush",
          summary: "你先赶往西市，以时间换取直接观察交易现场的机会。",
          stateDelta: delta({
            minutesElapsed: 40,
            moneyDelta: -5,
            reputationDeltas: { household: 0, market: 1, administration: 0 },
          }),
          relationshipMemories: [],
          riskClockDeltas: [{ id: "market-deadline", label: "西市交割期限", delta: 2, threshold: 5, resolve: false }],
          nextEventId: "merchant-gate-window",
          ending: null,
        },
      },
      {
        id: "choice-3",
        label: "先询问城门与市场时限",
        intent: "用制度边界决定是否立即行动",
        risk: "low",
        consequence: {
          key: "merchant-time-boundary",
          summary: "你先确认通行与市场时限，没有把制度背景说成今日的具体执法记录。",
          stateDelta: delta({
            minutesElapsed: 15,
            skillDeltas: { memory: 0, reasoning: 1, socialJudgment: 0, professionalPotential: 0, physical: 0, luck: 0 },
          }),
          relationshipMemories: [],
          riskClockDeltas: [{ id: "market-deadline", label: "西市交割期限", delta: 0, threshold: 5, resolve: false }],
          nextEventId: "merchant-gate-window",
          ending: null,
        },
      },
    ],
  },
  {
    eventId: "merchant-gate-window",
    chapterId: "merchant-first-ledger",
    originIds: ["merchant"],
    title: "交割窗口正在缩短",
    classification: "合理重建",
    prerequisites: [
      { kind: "origin_is", originId: "merchant" },
      { kind: "turn_between", min: 1, max: 1 },
    ],
    freeTextChoiceId: "choice-1",
    evidenceRefs: ["S-003", "S-004", "S-007"],
    publicationStatus: "published",
    choices: [
      {
        id: "choice-1",
        label: "请家庭管事共同复核",
        intent: "用关系信用降低误判风险",
        risk: "low",
        consequence: {
          key: "merchant-shared-audit",
          summary: "你让家庭管事参与复核，决策变慢，但留下了共同记忆。",
          stateDelta: delta({
            minutesElapsed: 30,
            relationshipDeltas: [{ id: "household-steward", label: "家庭管事", delta: 1 }],
            reputationDeltas: { household: 1, market: 0, administration: 0 },
          }),
          relationshipMemories: [{
            relationshipId: "household-steward",
            summary: "你在交割压力下仍邀请管事共同核验。",
            valence: "positive",
          }],
          riskClockDeltas: [{ id: "market-deadline", label: "西市交割期限", delta: 1, threshold: 5, resolve: false }],
          nextEventId: "merchant-settlement",
          ending: null,
        },
      },
      {
        id: "choice-2",
        label: "接受一笔小额损失换取延期",
        intent: "用有限金钱降低期限压力",
        risk: "medium",
        consequence: {
          key: "merchant-buy-time",
          summary: "你接受小额损失，换来继续核对的时间。",
          stateDelta: delta({ minutesElapsed: 20, moneyDelta: -12 }),
          relationshipMemories: [],
          riskClockDeltas: [{ id: "market-deadline", label: "西市交割期限", delta: -2, threshold: 5, resolve: false }],
          nextEventId: "merchant-settlement",
          ending: null,
        },
      },
      {
        id: "choice-3",
        label: "独自承担并立即交割",
        intent: "以个人判断换取速度",
        risk: "high",
        consequence: {
          key: "merchant-solo-settlement",
          summary: "你独自作出交割判断，速度更快，但家庭无法共同承担解释责任。",
          stateDelta: delta({
            minutesElapsed: 15,
            reputationDeltas: { household: -1, market: 1, administration: 0 },
          }),
          relationshipMemories: [{
            relationshipId: "household-steward",
            summary: "家庭管事记得你绕过了共同复核。",
            valence: "negative",
          }],
          riskClockDeltas: [{ id: "market-deadline", label: "西市交割期限", delta: 3, threshold: 5, resolve: false }],
          nextEventId: "merchant-settlement",
          ending: null,
        },
      },
    ],
  },
  {
    eventId: "merchant-settlement",
    chapterId: "merchant-first-ledger",
    originIds: ["merchant"],
    title: "第一笔责任如何落账",
    classification: "叙事虚构",
    prerequisites: [
      { kind: "origin_is", originId: "merchant" },
      { kind: "turn_between", min: 2, max: 2 },
    ],
    freeTextChoiceId: "choice-1",
    evidenceRefs: ["S-003", "S-004", "S-005"],
    publicationStatus: "published",
    choices: [
      {
        id: "choice-1",
        label: "把不确定性写进家庭账记",
        intent: "保留证据边界并结束本章",
        risk: "low",
        consequence: {
          key: "merchant-record-uncertainty",
          summary: "你把未能证实的部分单独记录，拒绝用确定口吻掩盖缺口。",
          stateDelta: delta({ minutesElapsed: 25, reputationDeltas: { household: 1, market: 0, administration: 0 } }),
          relationshipMemories: [],
          riskClockDeltas: [{ id: "market-deadline", label: "西市交割期限", delta: -4, threshold: 5, resolve: true }],
          nextEventId: null,
          ending: ending(
            "merchant-ending-audited-ledger",
            "留有缺口的账簿",
            "你没有把一次家庭交割写成可代表全部西市商人的历史。账簿留下了责任，也留下了不确定性。",
            ["S-003", "S-004", "S-005"],
          ),
        },
      },
      {
        id: "choice-2",
        label: "优先维护市场信用",
        intent: "承担损失并换取后续往来",
        risk: "medium",
        consequence: {
          key: "merchant-protect-credit",
          summary: "你承担有限损失，优先保住家庭在市场中的信用。",
          stateDelta: delta({ minutesElapsed: 20, moneyDelta: -18, reputationDeltas: { household: 0, market: 2, administration: 0 } }),
          relationshipMemories: [],
          riskClockDeltas: [{ id: "market-deadline", label: "西市交割期限", delta: -4, threshold: 5, resolve: true }],
          nextEventId: null,
          ending: ending(
            "merchant-ending-market-credit",
            "市场记住了这次承担",
            "你保住了市场信用，但付出的代价属于这个虚构家庭，不能外推为唐代商人的普遍选择。",
            ["S-003", "S-004"],
          ),
        },
      },
      {
        id: "choice-3",
        label: "把责任推回无名经手人",
        intent: "保住眼前财物但损害关系",
        risk: "high",
        consequence: {
          key: "merchant-shift-blame",
          summary: "你把责任推给无法核验的经手人，短期止损，长期关系受损。",
          stateDelta: delta({
            minutesElapsed: 10,
            relationshipDeltas: [{ id: "household-steward", label: "家庭管事", delta: -2 }],
            reputationDeltas: { household: -2, market: 0, administration: 0 },
          }),
          relationshipMemories: [{
            relationshipId: "household-steward",
            summary: "家庭管事记得你把无法核实的责任推给旁人。",
            valence: "negative",
          }],
          riskClockDeltas: [{ id: "market-deadline", label: "西市交割期限", delta: 0, threshold: 5, resolve: true }],
          nextEventId: null,
          ending: ending(
            "merchant-ending-fractured-household",
            "账平了，关系没有",
            "账面暂时平衡，家庭关系却留下裂痕。这个结局是受规则约束的叙事虚构，不是人物档案。",
            ["S-004", "S-005"],
          ),
        },
      },
    ],
  },
  {
    eventId: "craft-material-shortfall",
    chapterId: "craft-first-commission",
    originIds: ["craft"],
    title: "材料数目与工期对不上",
    classification: "合理重建",
    prerequisites: [
      { kind: "origin_is", originId: "craft" },
      { kind: "turn_between", min: 0, max: 0 },
      { kind: "location_is", locationId: "craft-ward" },
    ],
    freeTextChoiceId: "choice-1",
    evidenceRefs: ["S-003", "S-004", "S-008"],
    publicationStatus: "published",
    choices: [
      {
        id: "choice-1",
        label: "重新清点材料与工序",
        intent: "先判断短缺发生在哪一环",
        risk: "low",
        consequence: {
          key: "craft-recount-materials",
          summary: "你重新清点材料，把短缺从猜测变成可复核的问题。",
          stateDelta: delta({
            minutesElapsed: 30,
            skillDeltas: { memory: 0, reasoning: 1, socialJudgment: 0, professionalPotential: 1, physical: 0, luck: 0 },
          }),
          relationshipMemories: [],
          riskClockDeltas: [{ id: "workshop-deadline", label: "作坊交付期限", delta: 1, threshold: 5, resolve: false }],
          nextEventId: "craft-mentor-pressure",
          ending: null,
        },
      },
      {
        id: "choice-2",
        label: "立即向师长报告短缺",
        intent: "把责任与信息尽早共享",
        risk: "medium",
        consequence: {
          key: "craft-report-early",
          summary: "你尽早报告短缺，让师长可以参与决定。",
          stateDelta: delta({
            minutesElapsed: 15,
            relationshipDeltas: [{ id: "workshop-mentor", label: "作坊师长", delta: 1 }],
          }),
          relationshipMemories: [{
            relationshipId: "workshop-mentor",
            summary: "师长记得你没有隐瞒材料短缺。",
            valence: "positive",
          }],
          riskClockDeltas: [{ id: "workshop-deadline", label: "作坊交付期限", delta: 1, threshold: 5, resolve: false }],
          nextEventId: "craft-mentor-pressure",
          ending: null,
        },
      },
      {
        id: "choice-3",
        label: "先用替代材料试做",
        intent: "争取工期，但承担返工风险",
        risk: "high",
        consequence: {
          key: "craft-substitute-material",
          summary: "你用替代材料试做，争取时间，也把返工风险带入下一步。",
          stateDelta: delta({ minutesElapsed: 45, moneyDelta: -4, healthDelta: -1 }),
          relationshipMemories: [],
          riskClockDeltas: [{ id: "workshop-deadline", label: "作坊交付期限", delta: 3, threshold: 5, resolve: false }],
          nextEventId: "craft-mentor-pressure",
          ending: null,
        },
      },
    ],
  },
  {
    eventId: "craft-mentor-pressure",
    chapterId: "craft-first-commission",
    originIds: ["craft"],
    title: "师长要求你给出处理方案",
    classification: "合理重建",
    prerequisites: [
      { kind: "origin_is", originId: "craft" },
      { kind: "turn_between", min: 1, max: 1 },
    ],
    freeTextChoiceId: "choice-1",
    evidenceRefs: ["S-003", "S-004", "S-008"],
    publicationStatus: "published",
    choices: [
      {
        id: "choice-1",
        label: "提出分段交付方案",
        intent: "降低一次性交付失败的风险",
        risk: "low",
        consequence: {
          key: "craft-staged-delivery",
          summary: "你提出分段交付，让工期压力变得可管理。",
          stateDelta: delta({ minutesElapsed: 25, reputationDeltas: { household: 1, market: 0, administration: 0 } }),
          relationshipMemories: [{
            relationshipId: "workshop-mentor",
            summary: "师长记得你把压力拆成可执行步骤。",
            valence: "positive",
          }],
          riskClockDeltas: [{ id: "workshop-deadline", label: "作坊交付期限", delta: -1, threshold: 5, resolve: false }],
          nextEventId: "craft-delivery",
          ending: null,
        },
      },
      {
        id: "choice-2",
        label: "追加购买合适材料",
        intent: "用成本换取工序稳定",
        risk: "medium",
        consequence: {
          key: "craft-buy-materials",
          summary: "你用有限资金补足材料，减少工序变化。",
          stateDelta: delta({ minutesElapsed: 35, moneyDelta: -15 }),
          relationshipMemories: [],
          riskClockDeltas: [{ id: "workshop-deadline", label: "作坊交付期限", delta: -1, threshold: 5, resolve: false }],
          nextEventId: "craft-delivery",
          ending: null,
        },
      },
      {
        id: "choice-3",
        label: "承诺独自加快工序",
        intent: "用体力承担时间压力",
        risk: "high",
        consequence: {
          key: "craft-overwork",
          summary: "你承诺独自加快工序，期限压力下降，身体负担上升。",
          stateDelta: delta({ minutesElapsed: 60, healthDelta: -2, healthCondition: "strained" }),
          relationshipMemories: [],
          riskClockDeltas: [{ id: "workshop-deadline", label: "作坊交付期限", delta: 2, threshold: 5, resolve: false }],
          nextEventId: "craft-delivery",
          ending: null,
        },
      },
    ],
  },
  {
    eventId: "craft-delivery",
    chapterId: "craft-first-commission",
    originIds: ["craft"],
    title: "第一件交付物如何署名",
    classification: "叙事虚构",
    prerequisites: [
      { kind: "origin_is", originId: "craft" },
      { kind: "turn_between", min: 2, max: 2 },
    ],
    freeTextChoiceId: "choice-1",
    evidenceRefs: ["S-003", "S-004", "S-008"],
    publicationStatus: "published",
    choices: [
      {
        id: "choice-1",
        label: "如实记录参与工序的人",
        intent: "让责任与劳动对应",
        risk: "low",
        consequence: {
          key: "craft-credit-workers",
          summary: "你如实记录参与者，没有把共同劳动改写成个人功绩。",
          stateDelta: delta({
            minutesElapsed: 20,
            relationshipDeltas: [{ id: "workshop-mentor", label: "作坊师长", delta: 1 }],
            reputationDeltas: { household: 1, market: 0, administration: 0 },
          }),
          relationshipMemories: [{
            relationshipId: "workshop-mentor",
            summary: "师长记得你没有独占共同劳动。",
            valence: "positive",
          }],
          riskClockDeltas: [{ id: "workshop-deadline", label: "作坊交付期限", delta: -4, threshold: 5, resolve: true }],
          nextEventId: null,
          ending: ending(
            "craft-ending-shared-credit",
            "共同完成的第一件交付物",
            "你守住了工序和署名边界。具体作坊与人物仍是叙事参数，不能冒充考古发现。",
            ["S-003", "S-008"],
          ),
        },
      },
      {
        id: "choice-2",
        label: "接受师长代为署名",
        intent: "换取稳定，但个人贡献不可见",
        risk: "medium",
        consequence: {
          key: "craft-mentor-credit",
          summary: "你接受师长署名，交付平稳，个人贡献没有进入公开记忆。",
          stateDelta: delta({ minutesElapsed: 15, relationshipDeltas: [{ id: "workshop-mentor", label: "作坊师长", delta: 1 }] }),
          relationshipMemories: [],
          riskClockDeltas: [{ id: "workshop-deadline", label: "作坊交付期限", delta: -4, threshold: 5, resolve: true }],
          nextEventId: null,
          ending: ending(
            "craft-ending-invisible-labor",
            "没有署名的完成",
            "交付完成了，你的劳动却只留在关系记忆中。该结局不声称唐代工匠都处于同一署名制度。",
            ["S-003", "S-008"],
          ),
        },
      },
      {
        id: "choice-3",
        label: "把试做说成个人独创",
        intent: "争取名声并承担核验风险",
        risk: "high",
        consequence: {
          key: "craft-claim-invention",
          summary: "你把共同试做说成个人独创，短期获得注意，长期可信度下降。",
          stateDelta: delta({
            minutesElapsed: 10,
            relationshipDeltas: [{ id: "workshop-mentor", label: "作坊师长", delta: -2 }],
            reputationDeltas: { household: -2, market: 1, administration: 0 },
          }),
          relationshipMemories: [{
            relationshipId: "workshop-mentor",
            summary: "师长记得你夸大了个人贡献。",
            valence: "negative",
          }],
          riskClockDeltas: [{ id: "workshop-deadline", label: "作坊交付期限", delta: 0, threshold: 5, resolve: true }],
          nextEventId: null,
          ending: ending(
            "craft-ending-contested-credit",
            "被质疑的独创",
            "你得到短暂名声，也失去部分信任。结局只描述这个虚构角色，不替历史工匠群体发言。",
            ["S-003", "S-004", "S-008"],
          ),
        },
      },
    ],
  },
  {
    eventId: "clerk-ambiguous-place",
    chapterId: "clerk-first-dispatch",
    originIds: ["clerk"],
    title: "文书中的地名含混不清",
    classification: "合理重建",
    prerequisites: [
      { kind: "origin_is", originId: "clerk" },
      { kind: "turn_between", min: 0, max: 0 },
      { kind: "location_is", locationId: "jingzhao-fu" },
    ],
    freeTextChoiceId: "choice-1",
    evidenceRefs: ["S-002", "S-006", "S-008"],
    publicationStatus: "published",
    choices: [
      {
        id: "choice-1",
        label: "对照旧件核验地名",
        intent: "先排除抄写差异",
        risk: "low",
        consequence: {
          key: "clerk-compare-records",
          summary: "你先对照旧件，没有把含混字形直接解释为新地点。",
          stateDelta: delta({
            minutesElapsed: 25,
            skillDeltas: { memory: 1, reasoning: 1, socialJudgment: 0, professionalPotential: 0, physical: 0, luck: 0 },
          }),
          relationshipMemories: [],
          riskClockDeltas: [{ id: "dispatch-error", label: "文书误递风险", delta: 1, threshold: 5, resolve: false }],
          nextEventId: "clerk-delivery-range",
          ending: null,
        },
      },
      {
        id: "choice-2",
        label: "询问资深书手",
        intent: "用关系经验核对制度文本",
        risk: "medium",
        consequence: {
          key: "clerk-consult-scribe",
          summary: "你向资深书手求证，让含混问题进入共同核验。",
          stateDelta: delta({
            minutesElapsed: 20,
            relationshipDeltas: [{ id: "senior-scribe", label: "资深书手", delta: 1 }],
          }),
          relationshipMemories: [{
            relationshipId: "senior-scribe",
            summary: "资深书手记得你在不确定时主动求证。",
            valence: "positive",
          }],
          riskClockDeltas: [{ id: "dispatch-error", label: "文书误递风险", delta: 1, threshold: 5, resolve: false }],
          nextEventId: "clerk-delivery-range",
          ending: null,
        },
      },
      {
        id: "choice-3",
        label: "按最可能读法直接誊写",
        intent: "节省时间并承担误递风险",
        risk: "high",
        consequence: {
          key: "clerk-guess-copy",
          summary: "你按最可能读法誊写，速度更快，误递风险明显增加。",
          stateDelta: delta({ minutesElapsed: 10, reputationDeltas: { household: 0, market: 0, administration: -1 } }),
          relationshipMemories: [],
          riskClockDeltas: [{ id: "dispatch-error", label: "文书误递风险", delta: 3, threshold: 5, resolve: false }],
          nextEventId: "clerk-delivery-range",
          ending: null,
        },
      },
    ],
  },
  {
    eventId: "clerk-delivery-range",
    chapterId: "clerk-first-dispatch",
    originIds: ["clerk"],
    title: "递送范围仍需确认",
    classification: "合理重建",
    prerequisites: [
      { kind: "origin_is", originId: "clerk" },
      { kind: "turn_between", min: 1, max: 1 },
    ],
    freeTextChoiceId: "choice-1",
    evidenceRefs: ["S-002", "S-006", "S-008"],
    publicationStatus: "published",
    choices: [
      {
        id: "choice-1",
        label: "请经手人补写递送范围",
        intent: "让责任信息回到文书",
        risk: "low",
        consequence: {
          key: "clerk-request-clarification",
          summary: "你要求补写递送范围，把口头理解重新变成可复核文字。",
          stateDelta: delta({ minutesElapsed: 30, reputationDeltas: { household: 0, market: 0, administration: 1 } }),
          relationshipMemories: [],
          riskClockDeltas: [{ id: "dispatch-error", label: "文书误递风险", delta: -1, threshold: 5, resolve: false }],
          nextEventId: "clerk-register",
          ending: null,
        },
      },
      {
        id: "choice-2",
        label: "与资深书手共同标注疑点",
        intent: "保留疑点并继续流转",
        risk: "medium",
        consequence: {
          key: "clerk-mark-uncertainty",
          summary: "你与资深书手共同标出疑点，没有用无依据的确定性填补空缺。",
          stateDelta: delta({
            minutesElapsed: 20,
            relationshipDeltas: [{ id: "senior-scribe", label: "资深书手", delta: 1 }],
          }),
          relationshipMemories: [{
            relationshipId: "senior-scribe",
            summary: "你们共同保留了文书疑点。",
            valence: "positive",
          }],
          riskClockDeltas: [{ id: "dispatch-error", label: "文书误递风险", delta: 0, threshold: 5, resolve: false }],
          nextEventId: "clerk-register",
          ending: null,
        },
      },
      {
        id: "choice-3",
        label: "先递送，再口头解释",
        intent: "维持速度但削弱可追溯性",
        risk: "high",
        consequence: {
          key: "clerk-oral-fix",
          summary: "你先递送再口头解释，流程继续，但可追溯性下降。",
          stateDelta: delta({ minutesElapsed: 15, reputationDeltas: { household: 0, market: 0, administration: -1 } }),
          relationshipMemories: [],
          riskClockDeltas: [{ id: "dispatch-error", label: "文书误递风险", delta: 2, threshold: 5, resolve: false }],
          nextEventId: "clerk-register",
          ending: null,
        },
      },
    ],
  },
  {
    eventId: "clerk-register",
    chapterId: "clerk-first-dispatch",
    originIds: ["clerk"],
    title: "疑点是否进入登记",
    classification: "叙事虚构",
    prerequisites: [
      { kind: "origin_is", originId: "clerk" },
      { kind: "turn_between", min: 2, max: 2 },
    ],
    freeTextChoiceId: "choice-1",
    evidenceRefs: ["S-002", "S-006", "S-008"],
    publicationStatus: "published",
    choices: [
      {
        id: "choice-1",
        label: "把疑点与处理过程一并登记",
        intent: "保留责任链并结束本章",
        risk: "low",
        consequence: {
          key: "clerk-register-uncertainty",
          summary: "你把疑点和处理过程一并登记，让后续人知道哪些部分仍未证实。",
          stateDelta: delta({ minutesElapsed: 25, reputationDeltas: { household: 0, market: 0, administration: 2 } }),
          relationshipMemories: [],
          riskClockDeltas: [{ id: "dispatch-error", label: "文书误递风险", delta: -4, threshold: 5, resolve: true }],
          nextEventId: null,
          ending: ending(
            "clerk-ending-auditable-record",
            "可追溯的疑点",
            "你没有消除不确定性，而是让它变得可追溯。具体登记程序仍是叙事重建，不冒充出土文书。",
            ["S-002", "S-006", "S-008"],
          ),
        },
      },
      {
        id: "choice-2",
        label: "只改正结果，不保留争议过程",
        intent: "保持文书简洁并牺牲部分解释链",
        risk: "medium",
        consequence: {
          key: "clerk-correct-without-trace",
          summary: "你改正结果，却没有保留争议过程，文书更简洁，也更难复盘。",
          stateDelta: delta({ minutesElapsed: 15, reputationDeltas: { household: 0, market: 0, administration: 1 } }),
          relationshipMemories: [],
          riskClockDeltas: [{ id: "dispatch-error", label: "文书误递风险", delta: -3, threshold: 5, resolve: true }],
          nextEventId: null,
          ending: ending(
            "clerk-ending-clean-copy",
            "干净但缺少解释链的文书",
            "结果被改正，过程却没有留下。这个结局展示可追溯性的代价，不代表京兆府的统一程序。",
            ["S-002", "S-008"],
          ),
        },
      },
      {
        id: "choice-3",
        label: "让资深书手承担最终说明",
        intent: "降低个人责任并改变关系",
        risk: "high",
        consequence: {
          key: "clerk-transfer-responsibility",
          summary: "你把最终说明交给资深书手，个人风险下降，关系中的责任并未消失。",
          stateDelta: delta({
            minutesElapsed: 10,
            relationshipDeltas: [{ id: "senior-scribe", label: "资深书手", delta: -1 }],
          }),
          relationshipMemories: [{
            relationshipId: "senior-scribe",
            summary: "资深书手记得你把最后的说明责任交给了他。",
            valence: "negative",
          }],
          riskClockDeltas: [{ id: "dispatch-error", label: "文书误递风险", delta: -2, threshold: 5, resolve: true }],
          nextEventId: null,
          ending: ending(
            "clerk-ending-borrowed-authority",
            "借来的权威",
            "你借助资深书手结束争议，也留下责任转移的记忆。人物与细节均为叙事虚构。",
            ["S-002", "S-006", "S-008"],
          ),
        },
      },
    ],
  },
];

export const phase10EventTemplates: EventTemplate[] = rawEvents.map((event) =>
  eventTemplateSchema.parse(event)
);

const eventIndex = new Map(phase10EventTemplates.map((event) => [event.eventId, event]));

export function getFirstEventId(origin: OriginId): string {
  return phase10ScenarioManifest.firstEventByOrigin[origin];
}

export function getEventTemplate(eventId: string): EventTemplate {
  const event = eventIndex.get(eventId);
  if (!event) throw new Error(`event_not_found:${eventId}`);
  return event;
}
